# frozen_string_literal: true

appraise "metrics-sdk" do
end

appraise "metrics-api" do
  remove_gem "opentelemetry-metrics-sdk"
end

appraise "base" do
  remove_gem "opentelemetry-metrics-sdk"
  remove_gem "opentelemetry-metrics-api"
end
